# build-atomicbot-rocm71.ps1
# Rebuilds the AtomicBot llama.cpp (C:\llama-tq3) HIP backend with FULL
# FlashAttention support for RX 7800 XT (gfx1101 / RDNA3):
#   - GGML_HIP_ROCWMMA_FATTN=ON  -> rocWMMA WMMA FA kernel (fixes f16/f16
#     FLASH_ATTN_EXT gaps on RDNA3; requires rocWMMA headers)
#   - GGML_CUDA_FA_ALL_QUANTS=ON -> all quantized K/V FA combos (q4_1/q5_0/
#     q5_1/iq4_nl) instead of the default subset
# Baseline (old build-rocm71): 22454 probes / 7831 NOT SUPPORTED.
# Result: <SourceRoot>/<BuildDir>/bin/llama-server.exe (+ test-backend-ops.exe)
# NOTE: copies libhipblas.dll -> hipblas.dll next to the binaries (ROCm 7.x
# ships "libhipblas.dll" but ggml-hip.dll imports "hipblas.dll" by name).

param(
    [string]$SourceRoot = "C:\llama-tq3",
    [string]$BuildDir = "build-rocm71-fa",
    [string]$RocmRoot = "C:\Program Files\AMD\ROCm\7.1",
    [string]$GpuTarget = "gfx1101",
    # rocWMMA headers (git clone --depth 1 --branch rocm-7.1.1 https://github.com/ROCm/rocWMMA.git)
    [string]$RocwmmaInclude = "C:\llama-tq3-deps\rocWMMA\library\include",
    [switch]$Clean,
    # Only run cmake configure (no compile); useful to validate flags fast.
    [switch]$ConfigureOnly
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $SourceRoot)) {
    Write-Error "llama.cpp source not found: $SourceRoot"
    exit 1
}
if (-not (Test-Path $RocwmmaInclude)) {
    Write-Error "rocWMMA headers not found: $RocwmmaInclude (see clone command in header comment)"
    exit 1
}

# rocWMMA's version header is generated by its own CMake at install time.
# Generate it in-place so the raw clone works as an include-only dependency
# (version 2.1.0 = the rocm-7.1.x release line, see rocWMMA CMakeLists.txt).
$verHeader = Join-Path $RocwmmaInclude "rocwmma\rocwmma-version.hpp"
if (-not (Test-Path $verHeader)) {
    Write-Host "Generating rocwmma-version.hpp (2.1.0)..."
    @'
#ifndef ROCWMMA_API_VERSION_HPP
#define ROCWMMA_API_VERSION_HPP

#define ROCWMMA_VERSION_MAJOR       2
#define ROCWMMA_VERSION_MINOR       1
#define ROCWMMA_VERSION_PATCH       0

inline std::string rocwmma_get_version()
{
    return std::to_string(ROCWMMA_VERSION_MAJOR) + "." + std::to_string(ROCWMMA_VERSION_MINOR) + "."
           + std::to_string(ROCWMMA_VERSION_PATCH);
}

#endif // ROCWMMA_API_VERSION_HPP
'@ | Set-Content -LiteralPath $verHeader -Encoding ASCII
}

$clang   = (Join-Path $RocmRoot "bin\clang.exe")   -replace '\\', '/'
$clangxx = (Join-Path $RocmRoot "bin\clang++.exe") -replace '\\', '/'
$llvmRc  = (Join-Path $RocmRoot "bin\llvm-rc.exe") -replace '\\', '/'
foreach ($t in @($clang, $clangxx, $llvmRc)) {
    if (-not (Test-Path $t)) { Write-Error "Missing ROCm tool: $t"; exit 1 }
}

$buildPath = Join-Path $SourceRoot $BuildDir
if ($Clean -and (Test-Path $buildPath)) {
    Write-Host "Removing existing build dir: $buildPath"
    Remove-Item -LiteralPath $buildPath -Recurse -Force
}

# HIP device libraries are found via HIP_PATH / ROCM_PATH.
$env:HIP_PATH       = $RocmRoot
$env:ROCM_PATH      = $RocmRoot
$env:HIP_CLANG_PATH = Join-Path $RocmRoot "bin"
$env:PATH           = "$($env:HIP_CLANG_PATH);$env:PATH"

Write-Host "Configuring AtomicBot HIP build ($GpuTarget, ROCWMMA_FATTN=ON, FA_ALL_QUANTS=ON)..."
$cfgArgs = @(
    "-S", $SourceRoot,
    "-B", $buildPath,
    "-G", "Ninja",
    "-DCMAKE_C_COMPILER=$clang",
    "-DCMAKE_CXX_COMPILER=$clangxx",
    "-DCMAKE_RC_COMPILER=$llvmRc",
    "-DCMAKE_PREFIX_PATH=$RocmRoot",
    "-Dhip_DIR=$(Join-Path $RocmRoot 'lib\cmake\hip')",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DGGML_HIP=ON",
    "-DAMDGPU_TARGETS=$GpuTarget",
    "-DGGML_HIP_GRAPHS=ON",
    "-DGGML_HIP_MMQ_MFMA=ON",
    "-DGGML_HIP_NO_VMM=ON",
    "-DGGML_HIP_RCCL=OFF",
    "-DGGML_OPENMP=ON",
    # --- FlashAttention fixes ---
    "-DGGML_CUDA_FA_ALL_QUANTS=ON",
    "-DGGML_HIP_ROCWMMA_FATTN=ON",
    # .cu sources compile as LANGUAGE CXX under hipcc (see ggml-hip/CMakeLists.txt),
    # so the rocwmma include path must go into BOTH HIP and CXX flags.
    "-DCMAKE_HIP_FLAGS=-I$(($RocwmmaInclude -replace '\\', '/'))",
    "-DCMAKE_CXX_FLAGS=-I$(($RocwmmaInclude -replace '\\', '/'))"
)
& cmake @cfgArgs
if ($LASTEXITCODE -ne 0) { Write-Error "CMake configure failed"; exit $LASTEXITCODE }

if ($ConfigureOnly) {
    Write-Host "Configure-only mode: done."
    exit 0
}

Write-Host "Building llama-server + test-backend-ops (HIP)... This takes a while."
& cmake --build $buildPath --target llama-server test-backend-ops
if ($LASTEXITCODE -ne 0) { Write-Error "Build failed"; exit $LASTEXITCODE }

# Known ROCm 7.x Windows issue: ggml-hip.dll imports hipblas.dll by name but
# only libhipblas.dll is shipped. Copy it next to the binaries.
$libhipblas = Join-Path $RocmRoot "bin\libhipblas.dll"
$binDir     = Join-Path $buildPath "bin"
if ((Test-Path $libhipblas) -and -not (Test-Path (Join-Path $binDir "hipblas.dll"))) {
    Copy-Item $libhipblas (Join-Path $binDir "hipblas.dll")
    Write-Host "Copied libhipblas.dll -> bin\hipblas.dll"
}

$server = Join-Path $binDir "llama-server.exe"
if (Test-Path $server) {
    Write-Host "OK: AtomicBot FA-fixed llama-server built at $server" -ForegroundColor Green
    Write-Host "Verify with: test-backend-ops support  (expect far fewer NOT SUPPORTED)"
}
else {
    Write-Error "Build reported success but llama-server.exe not found at $server"
    exit 1
}
